version: "3"
service:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "Admin123"
      MYSQL_DATABASE: "hex_test"
    volumes:
      - ./testdb/:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"